### ISSUE TITLE
Filters on main class views

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#105]
I'd like us to add filters on top of the main class views. This will replace the ugly side menus we have currently.

Think of these as similar to the admin filters inside Joomla:
![ostraining_-_administration_-_article_manager__articles](https://cloud.githubusercontent.com/assets/3868028/12873826/8f2db52a-cd95-11e5-80ca-63ff78d08cdb.png)

Here's how they might appear in action:
![online_training_classes](https://cloud.githubusercontent.com/assets/3868028/12873829/96f04f66-cd95-11e5-8a52-9b6807fcfaee.png)

There would be some defaults. For example, the filter would default to show classes that the current student has not completed.

Also, when it comes to topics, maybe it can default to the last topic they were watching, "Drupal", "WordPress" for example.

**Comment by billtomczak** [comment]
@stevejburge About the topics filter. Since the pathway affects the url, that dropdown would really be a redirect to the selected page. For example, if they were on

> https://www.ostraining.com/classes/wordpress/

And selected 'Joomla' from a dropdown, they would be redirected to

> https://www.ostraining.com/classes/joomla/

For the same reason, If users go to

> https://www.ostraining.com/classes/

They now get a list of core pathways. Are you saying that you would rather see them redirected to the last pathway they visited? If so, they would only ever see the list of pathways and their descriptions the first time they visit /classes.

**Comment by stevejburge** [comment]
Yes, it could be a redirect, or we could use Ajax perhaps? This could be more like a search page.

**Comment by billtomczak** [comment]
That begins to sound like a completely different page. Right now /classes is a landing page that allows rooting the pathway lists (e.g. /classes/wordpress). This is part of the sitemap and affects SEO.

What you're describing would function very differently. Especially if we implement using ajax - which would be cool.

**Comment by stevejburge** [comment]
Yes, perhaps this is different enough to justify a new page. We can leave /classes/ as it is and create this on a fresh page.

I imagine this page to be far more dynamic. Something that automatically adjusts for each user.

**Comment by billtomczak** [comment]
yes that's what I was thinking. Does it make sense to still add some filters on the current /classes page?

**Comment by stevejburge** [comment]
Sure, although technically /classes/ is /pathways/ right?

**Comment by billtomczak** [comment]
Ah yeah - sorry - I meant on the pathway itself, such as /classes/wordpress. I'm thinking difficulty and completed filters as well as making each column sortable.

**Comment by stevejburge** [comment]
Yes, absolutely! I'd love to see this, please

**Comment by billtomczak** [comment]
@htmgarcia - please see initial setup for these filters. Let me know what you would like for html

**Comment by billtomczak** [comment]
@stevejburge - working filters implemented on ghostexplained. Please review. cool as the ajax idea was, ultimately it seemed like it would add too much complexity.

**Comment by stevejburge** [comment]
Great, thanks Bill. That's off to a great start.

Are we able to filter by finished / not-finished?

**Comment by billtomczak** [comment]
Yes - all the infrastructure is in place. Just need to implement it now :)

**Comment by billtomczak** [comment]
I was thinking to mimic the completed/in-progress/not-started selections you had mentioned elsewhere

**Comment by stevejburge** [comment]
Great. Thanks. 

I'm trying to visually think about the best way to handle it once we create many pathways.

For example, people might want to choose a "Drupal" filter that shows only Drupal pathways.

**Comment by billtomczak** [comment]
Ah - but that's what that top filter already is. Filters by pathway.

**Comment by stevejburge** [comment]
Sure. I guess my thought is ... what happens if 100 pathways, which is certainly conceivable.

Could we add a filter based on Tags, perhaps?

**Comment by stevejburge** [comment]
So my idea would be ... filter first on a Tag such as "Drupal" then next you'll only see Drupal pathways.

**Comment by billtomczak** [comment]
Sure. But I don't see how that makes sense on a pathway page - which is what I'm working on here. This is a single, specific pathway. 'Drupal' for example.

Where having lots of pathways becomes a problem would be on /classes. This is the list of pathways. It would make sense to me to have filters here based on tags.

**Comment by stevejburge** [comment]
Ok, sure. I guess my sights are a little higher.

My assumption will be that, when they're on a pathway page, they're in the right place.

My priority is: how do we make it easy for them to get to the right the pathway. So /classes/ is the key.

**Comment by billtomczak** [comment]
yes. I also can imagine an advanced search page,

**Comment by stevejburge** [comment]
Great, thanks. That's the key ... helping people drill down to the right class or pathway.

OK, like I say, I'm still trying to visually think about this, but here's a first draft ...

![drupal_videos](https://cloud.githubusercontent.com/assets/3868028/13652713/bb93f59a-e61b-11e5-8cca-d62925012d31.png)

**Comment by billtomczak** [comment]
yeeeessss.....I like

**Comment by billtomczak** [comment]
Definitely an advanced search page.

**Comment by billtomczak** [comment]
Can generate a list of links using ajax requests really easily for something like that.

**Comment by billtomczak** [comment]
fun! :)

**Comment by stevejburge** [comment]
Lol, thanks. I'm glad you think so.

I'm far from set on this. I'd definitely like more feedback from @nicksavov @andergmartins @htmgarcia and more on this. I might ask Stacey too.

This really will be an essential tool to help people navigate all our classes.

**Comment by billtomczak** [comment]
Maybe also a search module that could be placed wherever we want on the site.

**Comment by htmgarcia** [comment]
A basic filtering with ajax should be fine, it would provide a better UX than reloading all the page.

**Comment by htmgarcia** [comment]
[Envato adds filtering on the left sidebar](http://codecanyon.net/category/wordpress). It could be a better place - as a separate module.

**Comment by billtomczak** [comment]
Yes - that's exactly what I had in mind.

**Comment by billtomczak** [comment]
@steve - I think this one's all done. Maybe a little of the old @htmgarcia love is called for. Let me know when you want me to launch this on our site.

**Comment by stevejburge** [comment]
Thanks @billtomczak Let's keep working on the main search page (or module as @htmgarcia suggests), but I think it's a great start for the pathway pages.

One quick change ... for the "Completed" dropdown can we default to "Not Completed" so we hide all finished classes.

One quick bug too ... after selecting "Completed", I still got a "Continue this class" icon.

![screen shot 2016-03-09 at 8 10 12 pm](https://cloud.githubusercontent.com/assets/3868028/13656229/2b7ebfe0-e633-11e5-9227-fe94b36982ca.png)

**Comment by stevejburge** [comment]
Maybe the solution is this ... a search module.

You can filter by:

Freeform search
Pathway (dropdown) 
Tags (dropdown) ... we can add an access level for tags
Completed / Not completed (dropdown)
Author (dropdown)
Difficulty (dropdown)

**Comment by htmgarcia** [comment]
I like them more displayed on a separate module on the left.

**Comment by stevejburge** [comment]
@billtomczak @htmgarcia Agreed. It's been helpful to talk this through. A module does seem the best approach.

**Comment by billtomczak** [comment]
yeah - I've used this approach in the past and it works really well. I'll back out these filters and start in on the module.

**Comment by stevejburge** [comment]
Thanks for being flexible. Sometimes it takes seeing something actually on the screen to figure out the right approach.

**Comment by billtomczak** [comment]
lol - in my experience that's almost always the case.

I've created issue #187 for further development on this idea. I'll close this issue out when I complete removing these page filters.
