### ISSUE TITLE
Mark classes as completed, in progress or not started

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#106]
At the moment, we don't actively show where someone is with a class

So here: https://www.ostraining.com/myclasses/
![my_classes](https://cloud.githubusercontent.com/assets/3868028/12873853/52d19d66-cd96-11e5-9b7a-5a3c37adf801.png)

And here:
![online_training_classes](https://cloud.githubusercontent.com/assets/3868028/12873869/7753ad78-cd96-11e5-8902-225a9fc77080.png)

And here:
![online_training_classes2](https://cloud.githubusercontent.com/assets/3868028/12873874/937febf6-cd96-11e5-8a87-0190c5bb08a5.png)

**Comment by htmgarcia** [comment]
@stevejburge [what about this](https://github.com/OSTraining/OSCampus/issues/181) and skip this one:
![online_training_classes](https://cloud.githubusercontent.com/assets/3868028/12873869/7753ad78-cd96-11e5-8902-225a9fc77080.png)
This, in order to overwhelm with more elements.

**Comment by htmgarcia** [comment]
In short, the button would have three purposes: 

1. Link to the next lesson
2. Display the progress ("start", "continue", "watch again" - which means "class completed")
3. Better UX

**Comment by stevejburge** [comment]
Ah, nice thinking. 

If we do that, maybe we change the icons too?

A rewind button for watch again
A play button for start etc.

**Comment by htmgarcia** [comment]
Yes, we can use different icons too.

**Comment by billtomczak** [comment]
I think we've taken care of this one.
