### ISSUE TITLE
Certificate is not printing the user name

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSCampus#115]
Just tried to save a certificate I had before in Guru and there is no name printed on it. Not sure if it happens with new certificates emitted only by OSCampus.

[certificate-7757.pdf](https://github.com/OSTraining/OSCampus/files/121927/certificate-7757.pdf)

**Comment by nicksavov** [comment]
Confirmed

**Comment by nicksavov** [comment]
Looks like it's for new certificates too. Just tried it on Why Joomla and it's not showing the name.

**Comment by nicksavov** [comment]
https://github.com/OSTraining/OSCampus/blob/cb7cb2e56d51e534932f895bcbd4cd812c36b3f7/src/site/views/certificate/tmpl/default.php#L42

**Comment by billtomczak** [comment]
Thanks Nick - that was it. Missed that change from the original guru code
