### ISSUE TITLE
Default class image not added

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#128]
When the class image is not added, a placeholder should be displayed instead.
Example: https://www.ostraining.com/classes/drupal/d8-updating/

We have the placeholder image: https://github.com/OSTraining/OSCampus/blob/master/src/media/images/default-course.jpg

**Comment by billtomczak** [comment]
@htmgarcia -- really? I'm pretty sure this is working properly. Could you check again?

**Comment by billtomczak** [comment]
Verified as  problem
