### ISSUE TITLE
Lesson ordering is getting messed up

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#132]
This happened after Rod edited a class ...

![screen shot 2016-02-09 at 10 49 23 am](https://cloud.githubusercontent.com/assets/3868028/12921348/e161b82e-cf1a-11e5-86ed-2163c4f75ae0.png)

**Comment by billtomczak** [comment]
ping! Any additional reports on this?

**Comment by rodOST** [comment]
haven't tried it again :(

**Comment by billtomczak** [comment]
Okay - I'll see if I can reproduce this on the test site.

**Comment by billtomczak** [comment]
yes indeed - some pretty basic problems with ordering courses. bbbe52921c33390bec50fdfe0629ea4b0066cc62 should take care of it.

**Comment by nicksavov** [comment]
Nice fix, Bill!
