### ISSUE TITLE
Class completed but not completed

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#143]
I just completed the Why WordPress class (https://www.ostraining.com/classes/wordpress/why/). I viewed all the lessons (they all show as viewed too) and passed the quiz with 100%.

But, I didn't get an email notification. Also, in the dashboard it shows it in "My Classes", but not in "My Certificates".

*But*, when I click see all in "My Certificates", it's there and can be downloaded.

Additional info: I had viewed some of the lessons in Guru prior to moving to OSCampus. Today, I just started at the first lesson I hadn't viewed and clicked Next until the quiz. I completed the quiz today in OSCampus.

**Comment by nicksavov** [comment]
I just cycled through all the lessons. Same result.

**Comment by nicksavov** [comment]
Since we have the new video analytics, I also went through and played a tiny bit of each video, but change the result either.

**Comment by billtomczak** [comment]
Confirmed - because of the new video data, there are some issues and confusions about what constitutes a completed class. Looking into it.

**Comment by billtomczak** [comment]
I requested holding off on the emailing of certificates as it was a bit more complicated to implement than I hoped. See #82 

As for it not appearing in the dashboard. Everything seems to work fine for me. I would expect that if the certificate appears on the *See All" link, it should appear on the Dashboard page. I will review that piece and verify. If you are still not seeing your cert on the dashboard, create a new issue in OSDashboard.

**Comment by nicksavov** [comment]
Sorry, by emailing I meant including a link to the cert in an email message about completion of the class, rather than emailing an attachment of the cert. I'll comment in #82.

As to the dashboard, it now appears in the My Certificates area. I opened up https://github.com/OSTraining/OSDashboard/issues/11 for the My Classes area.
