### ISSUE TITLE
Show pathway alias while editing a course

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSCampus#147]
The alias is important so I can distinguish between multiple pathways with the same name. Could we concatenate it to the pathway name?
![ostraining - administration - oscampus edit course 2016-02-11 08-58-59](https://cloud.githubusercontent.com/assets/407131/12974796/ef502a7c-d09d-11e5-89e7-242049641b3e.png)

**Comment by billtomczak** [comment]
egh. pathways. We really need to have a conversation soon about how we're dealing with these. The amount of duplication that is happening here is getting disturbing.

**Comment by nicksavov** [comment]
We can do it in today's meeting.

**Comment by andergmartins** [comment]
Sounds good ;)

**Comment by andergmartins** [comment]
One way to reduce the duplication is probably making OSTeammate obey the Access field. But we still have the need to have custom pathways that will appear only in OSTeammate and not for OSCampus users, like the WordPress Beginner (osteammate-wp-beginner-installed), which doesn't include all WP courses set to public.

**Comment by billtomczak** [comment]
yep - but this is why we need to discuss how we are actually using pathways and how best to manage them. We co-opted pathways to get something accomplished in OSTeammate, but maybe something in between your original implementation and how we're doing things now is in order.

**Comment by billtomczak** [comment]
Closing this one because the original issue has been resolved.
