### ISSUE TITLE
SQL error while trying to save after add new pathway to a course

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSCampus#148]
I was editing a course and checked a new pathway to it. After save I see this:

Save failed with the following error: Column count doesn't match value count at row 1 SQL=INSERT INTO hfps_oscampus_courses_pathways (courses_id,pathways_id,ordering) VALUES ()
![ostraining - administration - oscampus edit course 2016-02-11 09-02-41](https://cloud.githubusercontent.com/assets/407131/12974846/6e4f0014-d09e-11e5-8338-6456771fc950.png)

I was adding a pathway. It seems to work well when unchecking a pathway.

**Comment by billtomczak** [comment]
More information to reproduce would be helpful. I'm not seeing this. But I'm reviewing the code.

**Comment by andergmartins** [comment]
I just tried again and wasn't able to reproduce it. Btw, I just opened the form, checked the new pathway and saved. Just that. ;)

**Comment by billtomczak** [comment]
thanks! This did result in some code improvements at least :)

I'll close this for now. If you find some specific sequence that causes a problem, just open a new issue.

**Comment by andergmartins** [comment]
Sounds good, tks ;)
