### ISSUE TITLE
Saving a course as copy shows a error message

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSCampus#149]
It saved, so I'm not sure it is really related to OSCampus or a cache cleaner method. But it displayed the following error message:

JFolder: :delete: Could not delete folder. Path: /home/ostraini/public_html/cache/sefadvance

**Comment by billtomczak** [comment]
That error pops up occasionally and isn't related to OSCampus. Either SEF Advance or some caching plugin.

That said -- I included save as copy but probably should disable it until further review. It scares me just a little bit :)

**Comment by stevejburge** [comment]
Yes, that's all SEF Advance and happens throughout the site

**Comment by nicksavov** [comment]
Thanks guys!
