### ISSUE TITLE
PHP arrays quiz is empty

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#150]
https://www.ostraining.com/classes/coding/php/php-arrays-quiz/ is empty

**Comment by nicksavov** [comment]
Issue fixed. I'll post the solution in slack since it needs some review.

**Comment by nicksavov** [comment]
Hmm, it's blank again.

**Comment by billtomczak** [comment]
Seems okay for me

**Comment by nicksavov** [comment]
Thanks Bill!
