### ISSUE TITLE
Error when creating new Lesson in Joomla! 3

### ISSUE THREAD

**Issue by puckett15** [OSTraining/OSCampus#151]
Steps to replicate: In Joomla! 3 go to OSCampus > Lessons > New and you will have this error:
![screen shot 2016-02-10 at 11 09 10 am](https://cloud.githubusercontent.com/assets/13893942/12982496/a2beb4c8-d0aa-11e5-9f4f-1b3aaea7f131.png)
I've tracked down where it's coming from and it should be in src/admin/models/lesson.php on line 21

**Comment by puckett15** [comment]
Everything that is getting put in $item is null on line 16 in that same file is null. 
![screen shot 2016-02-11 at 10 39 44 am](https://cloud.githubusercontent.com/assets/13893942/12982757/d5c6dbec-d0ab-11e5-9dbe-9377fb5eeade.png)

**Comment by billtomczak** [comment]
Thanks @puckett15 -- we aren't doing anything in J3 with OSCampus yet, but the code you pointed to did warrant some improvement. See if 82c04adcf9e1bade19af9fcc2537dca1cea5d95f takes care of this problem and let us know. If it does fix it, please close this issue.

**Comment by puckett15** [comment]
@billtomczak It does solve this particular issue, on letting me create a new lesson, but on the ui for creating a new lesson, php spits a few notices and warnings.

**Comment by billtomczak** [comment]
@puckett15  -Please create an issue for that with screenshots please

**Comment by nicksavov** [comment]
They are just strict standard issues and warnings. We can tackle them when planning the Joomla 3 move. They'll be easy to spot.

**Comment by billtomczak** [comment]
Except fixes for these kinds of errors are astonishingly quick and easy. And their presence indicates potentially more serious problems as I found looking into this. aebfb4fd65d2dec2c398c1140e3e904a1969b178

**Comment by nicksavov** [comment]
Ok, I'll find them and post in a bit. Kirby's done with his week and he'll be back on Monday.

**Comment by billtomczak** [comment]
See if that last commit fixed them.
