### ISSUE TITLE
Video is Broken for in Gimp for "Masking part-1"

### ISSUE THREAD

**Issue by manthri11** [OSTraining/OSCampus#152]
Tested on  "https://www.ostraining.com/classes/design/gimp-part-4/masking-1/"

The video is broken from 8:04 to 9:27
![video_is_broken](https://cloud.githubusercontent.com/assets/14900739/12984616/62dc26a8-d0a3-11e5-9095-bc059aa97cff.png)

**Comment by nicksavov** [comment]
Good catch, Madhu! This one is just for the video, rather than the LMS, so I've reported it to our trainer. I'll go ahead and close this ticket.

**Comment by manthri11** [comment]
Thanks
