### ISSUE TITLE
Videos in search results

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#155]
Continued from https://github.com/OSTraining/OSCampus/issues/101#issuecomment-183464543

**Comment by htmgarcia** [comment]
Thanks @nicksavov !

**Comment by billtomczak** [comment]
I believe this was resolved awhile ago.

**Comment by htmgarcia** [comment]
@billtomczak not sure about it, this issue is about integrating the video in search results in Google.

**Comment by billtomczak** [comment]
We did determine that the video meta data is automatically being incorporated into the video pages. Not sure what else we can do beyond that.

**Comment by htmgarcia** [comment]
Wonderful! I missed that.
