### ISSUE TITLE
Error Message when assigning class to a pathway.

### ISSUE THREAD

**Issue by puckett15** [OSTraining/OSCampus#159]
I'm getting this error message below, when assigning a class to a pathway. 
![screen shot 2016-02-15 at 9 13 49 am](https://cloud.githubusercontent.com/assets/13893942/13053598/f26523fe-d3ca-11e5-97a8-2f3b4112f9ab.png)
I created the pathway first, and then created the class. Also using Joomla! 2.5.

**Comment by puckett15** [comment]
@billtomczak  Yep that fixed it, I'm not super fluent in mysql commands yet, and how to write concise select queries, I honestly didn't know you could join other tables in a select query, but that did it! +1

**Comment by billtomczak** [comment]
Great to hear! Thanks again for working with us on this!
