### ISSUE TITLE
Figured out how to calculate certificate completion

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#160]
Feedback:
>  I just completed Drupal 7 beginner and i verified I passed all the quizzes and all videos show a viewed checkmark, however I did not receive the certificate. Did I miss a step or any thoughts?

**Comment by nicksavov** [comment]
Adding @stevejburge . This is related to https://secure.helpscout.net/conversation/170009464/16507/?folderId=390234

**Comment by billtomczak** [comment]
I think I have this pretty much sorted out. Create a new issue if anything crops up
