### ISSUE TITLE
2 descriptions clashing

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#161]
Maybe one should be over the other?
![screen shot 2016-02-15 at 5 05 00 pm](https://cloud.githubusercontent.com/assets/3868028/13061504/50e90dba-d406-11e5-851a-40776b9ecf25.png)

**Comment by billtomczak** [comment]
yep - that's the easiest way to solve this

**Comment by htmgarcia** [comment]
Why do we have two fields? A single field with readmore would make it more user friendly, I think.

**Comment by billtomczak** [comment]
We could do that. I want to have separate fields in the db because it makes things way easier and more efficient. But there's no reason I can't have the admin save code handle this for the user. So create a new issue :)

**Comment by htmgarcia** [comment]
Sure thing https://github.com/OSTraining/OSCampus/issues/163 :)
