### ISSUE TITLE
Merge description fields into one

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#163]
In the places where we are using "Introduction" and "Full description" it is possible to merge into one textarea, similar to articles.

> Intro text goes here
> [separator]
> Rest of the text

**Comment by htmgarcia** [comment]
Thank you @billtomczak !

**Comment by nicksavov** [comment]
@stevejburge , just keep in mind whenever you're creating/editing classes that whatever is above the readmore won't appear in the full description. It will only appear in the intro text.

**Comment by stevejburge** [comment]
@nicksavov @billtomczak Could we fix that? That's unexpected behavior compared to normal Joomla content

**Comment by billtomczak** [comment]
@nick are you sure? Take a look at https://www.ostraining.com/class/beginner/ for example. The text in the description pane is all the text for that class

**Comment by nicksavov** [comment]
Something wonky is going on. My changes to WordPress' Theme Design were lost from last night.

Let me check...

**Comment by nicksavov** [comment]
Hmm, looks like I made the change in GhostExplained?!

**Comment by nicksavov** [comment]
No, I did it in the live site, because I'm seeing part of the text change after the readmore and it's there.

**Comment by nicksavov** [comment]
Everything's working as expected now.

I'm not sure what the issue was, but I can't replicate it anymore. I guess we'll find out later if there some kind of bug or not. Let's close this one for now

**Comment by billtomczak** [comment]
I wonder if it might have been a caching issue?
