### ISSUE TITLE
Metadata boxes

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#166]
Everything looks good ...

![screen shot 2016-02-16 at 10 08 59 am](https://cloud.githubusercontent.com/assets/3868028/13080133/61cd0c8c-d495-11e5-8ef5-35bd7553170e.png)

Then you start typing and the description box jumps ...

![screen shot 2016-02-16 at 10 09 04 am](https://cloud.githubusercontent.com/assets/3868028/13080139/6ab0ce38-d495-11e5-8905-edf6c8b5f3bd.png)

**Comment by nicksavov** [comment]
I'm unable to replicate this in FF. Note that Steve usually uses Chrome and is on a larger screen.

**Comment by nicksavov** [comment]
I can't replicate it in Chrome either. I have a smaller monitor here though.

**Comment by htmgarcia** [comment]
To emulate biggers screens a zoom out can help.

**Comment by htmgarcia** [comment]
I wasn't able to replicate the issue with that technique.

**Comment by nicksavov** [comment]
Yeah, I tried the zoom earlier. It didn't work for me either.

**Comment by billtomczak** [comment]
I've been unable to replicate this on three different browsers at various zoom levels and window widths.

**Comment by stevejburge** [comment]
Ok, let's move on
