### ISSUE TITLE
How to handle quizzes

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#171]
I realize that I'd accidentally made a quiz "public"

What happens in that situation? Should we have a global setting to make sure all quizzes are at least "Registered"?

![screen shot 2016-02-19 at 11 04 01 am](https://cloud.githubusercontent.com/assets/3868028/13181021/0097e796-d6f9-11e5-9ee7-3ab5404b26e3.png)

**Comment by billtomczak** [comment]
On the lessons admin page, filter for quizzes. You can either sort or filter by access level.

Addressing #170 would be helpful for this.

**Comment by nicksavov** [comment]
There were 8 quiz there that I went ahead and fixed. Gotta love OSCampus!

**Comment by billtomczak** [comment]
Closing with the idea that #170 is a valid response
