### ISSUE TITLE
Codecitation plugin doesn't work in OSCampus

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#172]
Example, text below the video: https://www.ostraining.com/class/php/forms-sanitizing-results/

**Comment by htmgarcia** [comment]
I guess it;s matter of add support to content plugins.

**Comment by stevejburge** [comment]
@htmgarcia good find

@billtomczak Can we make this high priority?

**Comment by htmgarcia** [comment]
Thank you @billtomczak !
