### ISSUE TITLE
Design tweak for classes

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#173]
Could we tweak this?

1) Remove Beginner / Intermediate
2) Replace with the number of videos in the class
3) Put the "Start the class" on the same level as the main buttons. 

![screen shot 2016-02-23 at 3 57 13 pm](https://cloud.githubusercontent.com/assets/3868028/13266456/34e1f0a0-da46-11e5-8b82-8aec879d6d6f.png)

**Comment by htmgarcia** [comment]
I like number 3!

**Comment by stevejburge** [comment]
Thanks @htmgarcia 

I guess this might need to be part of 
https://github.com/OSTraining/OSCampus/issues/106 and also designing the new class images?

**Comment by htmgarcia** [comment]
For  2) Replace with the number of videos in the class is required @billtomczak magic :)

**Comment by billtomczak** [comment]
@htmgarcia -- lesson counts are now included and I added the label. You'll want to review.

**Comment by htmgarcia** [comment]
Thanks @billtomczak !
It seems the method is not available for new classes. Same case as #185

**Comment by billtomczak** [comment]
I think we're all set on this one now.

**Comment by htmgarcia** [comment]
You're the man. Thanks Mr. B!

**Comment by nicksavov** [comment]
I'm not seeing the changes at OST. I'm likely missing some detail from the above conversation, but I'll reopen in case this accidentally got missed.

**Comment by billtomczak** [comment]
Nope - only implemented on ghostexplained at the moment.
