### ISSUE TITLE
Improve myclasses/

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#174]
Let's give people more information for https://www.ostraining.com/myclasses/

In Progress or complete?
Which Pathway?

Maybe add filters?

**Comment by billtomczak** [comment]
Pathway has no relationship to a class. Especially now that we've fixed the urls to avoid reference to pathways. Users can arrive at any class via any pathway.

**Comment by stevejburge** [comment]
Ok, good point. Maybe just "In Progress" or "Complete"?

Perhaps later we can add another table with a list of which pathways they're taking

**Comment by billtomczak** [comment]
I'm already keeping a log of user activity per lessons where all sorts of information could be stored. But I'm not convinced that pathway as a piece of information makes much sense as things are organized. I could save the last pathway list the user visited and/or if they arrived at the current class via a pathway link. But that would be spotty and not entirely reliable. Plus, if someone arrives via at a class/lesson a direct link - like from a text search - no pathway is involved at all.

**Comment by htmgarcia** [comment]
@stevejburge @billtomczak I think this is something to work in [this branch](https://github.com/OSTraining/OSCampus/tree/progress-bar)

**Comment by billtomczak** [comment]
+1 @htmgarcia

**Comment by htmgarcia** [comment]
@stevejburge may you confirm if [this previous issue](https://github.com/OSTraining/OSCampus/issues/106) is related?

**Comment by stevejburge** [comment]
Yes, please. This would be really useful info for users

**Comment by htmgarcia** [comment]
I'm closing this issue and working from https://github.com/OSTraining/OSCampus/issues/106
