### ISSUE TITLE
Check the design for this improvement

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#176]
https://github.com/OSTraining/OSCampus/issues/164

**Comment by htmgarcia** [comment]
@billtomczak the class attribute is not being picked up https://github.com/OSTraining/OSCampus/commit/83b23986503397e9e14e18af8f40b6805cd76293#diff-ecbbfca7d7627a5ae0b0efeed5e9f3efR58

You can try in the test site: /mycertificates
In addition, the "Click here to start" link points to a 404 page.
<img width="741" alt="screen shot 2016-04-04 at 5 16 59 pm" src="https://cloud.githubusercontent.com/assets/4999794/14265772/0ece312c-fa89-11e5-8f20-eb9e25b43276.png">

**Comment by billtomczak** [comment]
:) See that last commit ffeb03bd4bffebf7ce69a9dad2b0653c3c183279

Parentheses were in the wrong order

**Comment by billtomczak** [comment]
Also b4e52ac2f126cbf5f34aa4c301b9abb1563bf3e9 fixes the link issue in two views including this one.

**Comment by htmgarcia** [comment]
Thanks for catching that @billtomczak !
