### ISSUE TITLE
Integrate with OSEmbed

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#177]
This seems like the most logical way to make OSCampus useful in the most situations ... 

After we move to Joomla 3, can we consider using an OSEmbed field for lessons in OSCampus.

That would allow people to add almost anything they wanted into lessons: Wistia, Vimeo, YouTube, presentations

cc @andergmartins @billtomczak

**Comment by andergmartins** [comment]
Looks good to me. The way I understand Bill constructed OSCampus, would make that easy. Bill can confirm, but he created with "flexibility" in mind. On the OSEmbed side, I just need to make sure to support the Wistia videos. The additional controls for autoplay, download, etc... can be moved to a OSEmbed plugin, and use the embed options button which I'm planning to create, to configure.

In OSCampus, maybe won't require any/or few changes. I think we already have a type of class where you can put text. If that class triggers the "onContentPrepare" that is all we need.

**Comment by billtomczak** [comment]
Creating a new lesson type of OSEmbed should be relatively easy. But I don't think trying to support Wistia via OSEmbed makes any sense. 

The home/previous/next buttons require a bunch of management/setup code in both php and js and require deeper knowledge of OSCampus data. Why should OSEmbed (or OSWisita) be responsible for drawing those buttons? Or caring about them at all. It's all code that would have to be moved at the very least.

I can see creating a new OSEmbed lesson type, that should be relatively easy. But I think trying to  fold the wistia videos into it would be a bit of a nightmare.

**Comment by stevejburge** [comment]
Ok, thanks. No rush on this. Wouldn't even practical until we've moved to Joomla 3.
