### ISSUE TITLE
Add language strings

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#180]
https://github.com/OSTraining/OSCampus/blob/master/src/site/views/course/tmpl/default.php#L29
https://github.com/OSTraining/OSCampus/blob/master/src/site/views/course/tmpl/default.php#L31
https://github.com/OSTraining/OSCampus/blob/master/src/site/views/course/tmpl/default.php#L33
https://github.com/OSTraining/OSCampus/blob/master/src/site/views/course/tmpl/default.php#L36

**Comment by billtomczak** [comment]
Nice catch @htmgarcia
