### ISSUE TITLE
Dynamic "Start this class" button

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#181]
For example, if a user already watched the first 3 videos, this button would say "Continue the class" and the link would point to the last watched lesson.

**Comment by htmgarcia** [comment]
![watch](https://cloud.githubusercontent.com/assets/4999794/13586978/555c2776-e48a-11e5-9b8c-4da38c3b8f91.jpg)

**Comment by billtomczak** [comment]
And I assume 'Watch again' would be for completed courses?

**Comment by htmgarcia** [comment]
Yes, that's correct.

**Comment by billtomczak** [comment]
Changes made on our staging site. The button is dynamic now, but now I have to figure out how to determine the last lesson they were on during their last visit.

**Comment by billtomczak** [comment]
@stevejburge @htmgarcia -- I think this is related to #106? Can we consolidate?

**Comment by htmgarcia** [comment]
@billtomczak that's correct!

**Comment by billtomczak** [comment]
Most of this is done I think except for this last issue #188

**Comment by nicksavov** [comment]
Great suggestion, Valentin! I'm glad Bill's able to implement excellent improvements like this.

I'm not seeing the change on OSTraining. I'm guessing we've moved to an upgrade at milestone workflow, rather than incremental (make live right away) workflow? That's totally fine, just checking so I know whether to reopen or not.

**Comment by billtomczak** [comment]
It's a bit chaotic. For me depends on the extent of the changes in the code. I got nailed earlier this week by some bad de-syncing of the code between staging and live. There have been some pretty deep changes in the last few days and I've been a bit more cautious than usual.

**Comment by nicksavov** [comment]
Got it, thanks!
