### ISSUE TITLE
Search Module

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/OSCampus#187]
From @stevejburge 

> filter by:

>Freeform search
Pathway (dropdown) 
Tags (dropdown) ... we can add an access level for tags
Completed / Not completed (dropdown)
Author (dropdown)
Difficulty (dropdown)

**Comment by billtomczak** [comment]
@stevejburge

By 'author' you mean 'teacher' correct?

For the freeform search - the usual search in title and description fields? in both courses and their lessons?

**Comment by stevejburge** [comment]
Yes, if feasible, please

**Comment by billtomczak** [comment]
Quite feasible! :)
