### ISSUE TITLE
Long pages forget which page their on

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#193]
If I'm editing lessons and there's more than 50, OSCampus will forget that I'm on the 2nd page

![screen shot 2016-03-15 at 9 17 21 am](https://cloud.githubusercontent.com/assets/3868028/13778936/e0c0ebb2-ea8e-11e5-990e-f34e1aa976c7.png)

**Comment by billtomczak** [comment]
@stevejburge I think I've fixed this. If not reopen this issue
