### ISSUE TITLE
Dress up the no search results message

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/OSCampus#194]

**Comment by htmgarcia** [comment]
<img width="744" alt="screen shot 2016-03-15 at 2 06 47 pm" src="https://cloud.githubusercontent.com/assets/4999794/13792487/ae0ef366-eab7-11e5-9742-fadaeb7761d8.png">

**Comment by htmgarcia** [comment]
<img width="735" alt="screen shot 2016-03-15 at 2 06 22 pm" src="https://cloud.githubusercontent.com/assets/4999794/13792498/b860536e-eab7-11e5-8647-0bf587a1d493.png">

**Comment by htmgarcia** [comment]
@billtomczak the blue button ("Start this class") is missing here:
<img width="744" alt="screen shot 2016-03-15 at 2 06 47 pm" src="https://cloud.githubusercontent.com/assets/4999794/13792512/c63896c2-eab7-11e5-9b57-f7131b655fdf.png">

**Comment by billtomczak** [comment]
weird. I'm not seeing this problem on either the search view or pathway view.

**Comment by billtomczak** [comment]
Although as noted in chat, the search view needs a review by you.

![search](https://cloud.githubusercontent.com/assets/3068131/13792623/f3593e34-eaaf-11e5-9667-4370e4dc17ad.png)

**Comment by htmgarcia** [comment]
I fooled myself. I forgot to login - lol

Your screenshot is correct. Now, I'll see how to display the blue button on the same line as the grey labels.

**Comment by htmgarcia** [comment]
@billtomczak why do we use this if() here: https://github.com/OSTraining/OSCampus/commit/a9e4e125bbf05a0df731eca2a2d03bd994e48866#diff-57134b6733e159886cfae6b33c2b4487R61
but not here: https://github.com/OSTraining/OSCampus/blob/development/src/site/views/pathway/tmpl/default.php#L66 ?

Sorry for being picky. I'm just curious.

**Comment by billtomczak** [comment]
I don't rightly know! I don't see why we would want to bother. I had copied the code from the pathway view for the search view. Due to branch history, I might have copied some version before a fix. Reviewing now and will fix this up

**Comment by billtomczak** [comment]
I copied the search template from the New Classes view. But I'm not sure why I included that test there either :) -- okay - time to rework these templates to get something a bit DRYer.

**Comment by htmgarcia** [comment]
Thanks @billtomczak !

**Comment by billtomczak** [comment]
btw @htmgarcia - you never have to apologize for being too picky. :)

**Comment by billtomczak** [comment]
Copied the html from search view to `New Classes` and `Pathway` views dc9d76e7f7824720e5c08520420642492b2a68b6
