### ISSUE TITLE
Check styling for search module buttons

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/OSCampus#195]

**Comment by htmgarcia** [comment]
Still there is an issue in smaller screens:
<img width="194" alt="screen shot 2016-03-15 at 1 38 51 pm" src="https://cloud.githubusercontent.com/assets/4999794/13791584/77fb361c-eab3-11e5-8f8f-41aa8eb00b9b.png">

**Comment by htmgarcia** [comment]
<img width="218" alt="screen shot 2016-03-15 at 1 55 18 pm" src="https://cloud.githubusercontent.com/assets/4999794/13792084/bd5bafc8-eab5-11e5-9e1b-2023899fbd0f.png">
