### ISSUE TITLE
Number of lessons

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#196]
Not sure this is quite right ...
![screen shot 2016-03-16 at 9 54 05 am](https://cloud.githubusercontent.com/assets/3868028/13814548/1480fe8c-eb5d-11e5-99f3-c6bbfd2ef888.png)

**Comment by nicksavov** [comment]
Strange, it's showing as 49 here.

**Comment by billtomczak** [comment]
@stevejburge  -- if you were not logged in, this may be a consequence of caching issues.
