### ISSUE TITLE
Ordering of pathways in search

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#197]
1) Could we put "Tags" at the top?

2) Could we go according to the Pathway ordering in the admin? Right now, there's no order ...

![screen shot 2016-03-16 at 12 35 16 pm](https://cloud.githubusercontent.com/assets/3868028/13820630/9c0e72a0-eb74-11e5-8b14-1498478fbd69.png)

**Comment by billtomczak** [comment]
lol - used the wrong ordering field for pathways. No surprise it came out a bit random looking!
