### ISSUE TITLE
My classes - small numbers

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#199]
The small % numbers are hard to see ... white on grey
![screen shot 2016-03-16 at 2 08 49 pm](https://cloud.githubusercontent.com/assets/3868028/13823588/acad84a0-eb80-11e5-8eea-f13b6600cf6f.png)

**Comment by htmgarcia** [comment]
Something we can do is hide the part of the number when the percentage is very low:
<img width="714" alt="screen shot 2016-03-16 at 12 36 19 pm" src="https://cloud.githubusercontent.com/assets/4999794/13824469/cc7cbac4-eb73-11e5-8cbe-710ffff1637f.png">
The complete number will be visible until the % bar is enough long.
