### ISSUE TITLE
UI Improvements for search form

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#200]
Starter proposal:
<img width="230" alt="screen shot 2016-03-16 at 12 25 31 pm" src="https://cloud.githubusercontent.com/assets/4999794/13824121/4fe9d1aa-eb72-11e5-9d38-e2b8ba8c0885.png">
Stad out the used fields, and make lighter the rest.

cc/ @stevejburge

**Comment by stevejburge** [comment]
@htmgarcia thumbs up

**Comment by htmgarcia** [comment]
@billtomczak how hard would be to automatically add a CSS class to each field to differenciate an empty/unused fields from the others?
![classes](https://cloud.githubusercontent.com/assets/4999794/13824379/5f1ec7b0-eb73-11e5-8bfd-f03c89cfcf35.jpg)

**Comment by billtomczak** [comment]
Easy. But I will use active/inactive rather than enabled/disabled which have a different meaning.

**Comment by billtomczak** [comment]
@htmgarcia new classes applied

**Comment by htmgarcia** [comment]
Thank you Sir!

**Comment by htmgarcia** [comment]
All good. Except "Completion" is not switching to the active class

**Comment by htmgarcia** [comment]
Actually only while selecting "Not started"

**Comment by billtomczak** [comment]
Sorry about that! Second time I made that same mistake :)

**Comment by htmgarcia** [comment]
Don't worry. Is part of the test process :)

**Comment by nicksavov** [comment]
Looks like this one is working now and can be closed.

**Comment by billtomczak** [comment]
yep

**Comment by htmgarcia** [comment]
Thanks guys!
