### ISSUE TITLE
UX Issue: Using Clear on Video Search

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#202]
Clicking Clear requires clicking Search afterward to display results of the Clear.

Steps to replicate:
1) Go to the Drupal videos
2) Enter Feeds into the search
3) Click Clear. The results still show as " No classes match your selection "

**Comment by billtomczak** [comment]
We could certainly submit the form on clicking the clear button. My thinking was that it should only clear the form allowing the user to make new selections. If the form is submitted on clear, it will take the user to /classes.

**Comment by nicksavov** [comment]
I guess I just expected it to clear the filters and load the changes. I understand that it's a choice and it would be desirably different for most people. Also, after the initial use, people would get accustomed to the design choice. I thought that most people would expect it the way I expected it though (that sounds very egocentric, lol).

**Comment by nicksavov** [comment]
btw, whatever choice is made is fine! I'll switch this to a question, instead of a bug report.

**Comment by billtomczak** [comment]
Yeah - there are some competing issues here. Submission of the search form navigates to any one of several page choices - /classes, /classes/<PATHWAY> or /component/oscampus/search. From my backend-y, engineer's perspective, I wanted to avoid what seemed like an unnecessary page refresh.

@stevejburge  gets to be the final decider I guess. I'll do whatever you guys tell me to :)

**Comment by nicksavov** [comment]
Closing in favor of making all of them onchange:
https://github.com/OSTraining/OSCampus/issues/219
