### ISSUE TITLE
Bug with saving quizzes

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#206]
So I ended up posting the wrong answer for several quiz questions. I just realized why ...

I choose a answer ...

![screen shot 2016-03-18 at 1 48 55 pm](https://cloud.githubusercontent.com/assets/3868028/13887110/67a456a4-ed10-11e5-81b1-fdda3c2b7dae.png)

Click Save. And OSCampus jumps back to selecting the first choice ...

![screen shot 2016-03-18 at 1 49 07 pm](https://cloud.githubusercontent.com/assets/3868028/13887123/75aa63ba-ed10-11e5-935c-6cbfa158fcb6.png)

This only seems to happen on the first save

**Comment by billtomczak** [comment]
Should be okay now. Reopen if you are still having issues.
