### ISSUE TITLE
[J3 Migration] Filter module design issue

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#210]
<img width="222" alt="new_classes" src="https://cloud.githubusercontent.com/assets/4999794/13892914/2ae2e18a-ed20-11e5-84ff-699322ed6525.png">

**Comment by htmgarcia** [comment]
@billtomczak what's the new issue?

**Comment by billtomczak** [comment]
Not a new issue. I accidentally closed this and wasn't sure you were finished. If you are then let's close it!

At the moment I have the module disabled due to some major reconstruction causing fatal errors so I can't check right away.
