### ISSUE TITLE
"Click here to start" link is broken

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#213]
![screen shot 2016-03-22 at 7 43 02 am](https://cloud.githubusercontent.com/assets/3868028/13950545/04c9b124-f002-11e5-820a-f45ef1e82c03.png)

**Comment by htmgarcia** [comment]
Probably a side effect about moving OSCampus to lower version.

**Comment by stevejburge** [comment]
I've fixed with a redirect in SEF Advance for now

**Comment by billtomczak** [comment]
Sadly was a problem from the beginning. Fixed now
