### ISSUE TITLE
pathways are oddly organized in the search

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#216]
![screen shot 2016-03-22 at 3 21 30 pm](https://cloud.githubusercontent.com/assets/3868028/13964775/cef579f8-f041-11e5-9d60-c33b73be9e30.png)

**Comment by htmgarcia** [comment]
A-Z would be a better ordering.

**Comment by billtomczak** [comment]
Pathways are being ordered by admin pathway ordering. @stevejburge, your call

**Comment by stevejburge** [comment]
Sorry, I guess we're referring to the tags in the drop down




On Tuesday, March 22, 2016, Bill Tomczak <notifications@github.com> wrote:

> Pathways are being ordered by admin pathway ordering. @stevejburge
> <https://github.com/stevejburge>, your call
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OSTraining/OSCampus/issues/216#issuecomment-200062780>
>


-- 

--
Steve Burge
CEO | OSTraining
steve@ostraining.com | +1 678-830-2168 ( extension 701 )

**Comment by billtomczak** [comment]
Yeah - when we were filtering on pathways directly, you wanted those ordered by pathway ordering. I unthinkingly - and obviously inappropriately - carried your request over to the topics filter. So I just fixed it.
