### ISSUE TITLE
The read more link is broken on some classes

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#217]
It seems to actually be deleting some parts of the text after saving

![screen shot 2016-03-22 at 3 22 57 pm](https://cloud.githubusercontent.com/assets/3868028/13964844/24e89a84-f042-11e5-85d2-9a6a2a6d853a.png)

**Comment by stevejburge** [comment]
So I enter a read more link ...

![screen shot 2016-03-22 at 5 09 52 pm](https://cloud.githubusercontent.com/assets/3868028/13968096/058fab82-f051-11e5-80ab-5e8e9301c0c8.png)

Then I click save and ....

![screen shot 2016-03-22 at 5 10 07 pm](https://cloud.githubusercontent.com/assets/3868028/13968099/0f5aba94-f051-11e5-8775-a7df95c8d9e5.png)

**Comment by htmgarcia** [comment]
Note, is not recommended that the readmore is inside a < p > tag, because would break the HTML when only intro is being displayed.

**Comment by htmgarcia** [comment]
The safe way is to be sure it follows this pattern:
```
<p>Intro text here...</p>
[ READMORE ]
<p>More text...</p>
```

**Comment by billtomczak** [comment]
This has been fixed by 54fabd1f1371e4ab2931d7d053bb042d1204135f and already applied to live site

**Comment by htmgarcia** [comment]
Good one @billtomczak !
My suggestions above still applies for good practices.

**Comment by billtomczak** [comment]
@htmgarcia that format for the readmore tag is not recognized

**Comment by billtomczak** [comment]
But yeah - avoid breaking up html!

**Comment by htmgarcia** [comment]
lol - I know. By `[ READMORE ]` I mean the actual `<hr id="system-readmore" />`

**Comment by billtomczak** [comment]
lol - sorry - I should have know

**Comment by htmgarcia** [comment]
Don't worry. I was being picky!

I hope one day Joomla switch to the WP way, which is way safer:
`<!-- readmore -->`
