### ISSUE TITLE
UI for quiz is messed up in Joomla 3

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#220]
![screen shot 2016-03-24 at 12 26 49 pm](https://cloud.githubusercontent.com/assets/4999794/14027210/1ede37ae-f1bc-11e5-97b3-42c7aa3757cf.jpg)

**Comment by htmgarcia** [comment]
@stevejburge officially we will support only Joomla 3, right? In that way I can focus on fixing design issues for that version

**Comment by stevejburge** [comment]
Yes, good news for @andergmartins. Joomla 2.5 is dead to us now.

**Comment by nicksavov** [comment]
Looks good to me. Is this still an issue? If so, on which specific quiz?

**Comment by billtomczak** [comment]
Yes - looks like this has been taken care of
