### ISSUE TITLE
Codecitation not working in OSCampus

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#224]
It's stripping almost everything out:
https://www.ostraining.com/class/sass/html/

**Comment by billtomczak** [comment]
This looks to me like a problem in codecitation. OSCampus is doing a standard content prepare using Joomla FW. There isn't much I can do here

**Comment by billtomczak** [comment]
I did an edit to the lesson that at least changed the output. Not sure what's going on there, but I'm 99% sure the solution is in codecitation

**Comment by stevejburge** [comment]
Strange. Here's codecitation inside an article: https://www.ostraining.com/blog/coding/extract-image-php/

Any suggestions for how to approach solving this?

**Comment by billtomczak** [comment]
Try putting the content of that lesson into an article and see the result. If it works there (and I doubt it will) then I'll revisit. But it's something in condecitation's parsing of that particular html code that is the problem.

**Comment by billtomczak** [comment]
Similarly, if you were to put the text of that article into the lesson description, I'm close to certain you'll find it works fine. Again, if you can show otherwise, I'll revisit.

**Comment by billtomczak** [comment]
Please see https://www.ostraining.com/class/sass/bill-test/

This is codecitation examples taken from the problem lesson and from the article you pointed out. As you can see, the php code works fine but the html code is not being handled well by codecitation.

**Comment by billtomczak** [comment]
Deeming this a codecitation problem. Closing in deference to OSTraining/plg_content_oscodecitation/issues/5
