### ISSUE TITLE
Can't save quiz questions

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#225]
Save failed with the following error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 7 SQL=SELECT lesson.id FROM hfps_oscampus_modules AS module INNER JOIN hfps_oscampus_lessons AS lesson ON lesson.modules_id = module.id WHERE module.courses_id IN ( SELECT courses_id FROM hfps_oscampus_modules WHERE id = 477) AND lesson.alias = 'sass-quiz' AND lesson.id !=

**Comment by billtomczak** [comment]
This looks to be the same issue as #227
