### ISSUE TITLE
Pathway pages are very slow

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#226]
Everywhere else in OSCampus is snappy, but pathway pages with multiple classes can be pretty slow to load.

The same is true of /myclasses/ when it gets busy.

**Comment by billtomczak** [comment]
@stevejburge @nicksavov - Status?

Has implementing pagination helped at all?

**Comment by stevejburge** [comment]
Yes, it seems to, although pagination is now broken in the admin of OSCampus

**Comment by billtomczak** [comment]
See #259
