### ISSUE TITLE
Still seeing some odd % in /myclasses/

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#230]
![screen shot 2016-03-29 at 6 24 08 am](https://cloud.githubusercontent.com/assets/3868028/14105021/f5c1a41e-f576-11e5-9774-b2bcee656c96.png)

**Comment by billtomczak** [comment]
This was due to some duplicate log entries that were imported from the original guru data. As far as I can tell it only affected one user and the database has been corrected using some best guesses.

If any additional problems like this show up, please open a new issue
