### ISSUE TITLE
Class UI problem on small screens

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#231]
![screen shot 2016-03-29 at 9 36 10 am](https://cloud.githubusercontent.com/assets/3868028/14109789/bc84c738-f591-11e5-9b82-1e3ba09a07d0.png)

**Comment by htmgarcia** [comment]
Guys, do you want me to see how can I improve this screen, or there is a standard way in Joomla 3 to fix it? @billtomczak

**Comment by stevejburge** [comment]
@htmgarcia @billtomczak Maybe put these behind tabs?

**Comment by htmgarcia** [comment]
Yes, that's sounds much better!

**Comment by billtomczak** [comment]
We're using standard J3 css classes/formatting. Putting them behind some additional tabs would probably be the easiest way to fix this.

**Comment by stevejburge** [comment]
@htmgarcia possible to fix next week? I bump into this a lot

**Comment by htmgarcia** [comment]
@stevejburge I think moving these columns into tabs is @billtomczak's territory.
