### ISSUE TITLE
Uploading Files

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#235]
This interface is confusing. Needs labels on the boxes?
![screen shot 2016-03-29 at 5 12 59 pm](https://cloud.githubusercontent.com/assets/3868028/14124059/9fa78a16-f5d1-11e5-8e58-12023caa6c84.png)

**Comment by htmgarcia** [comment]
@stevejburge placeholders inside the fields can works.

**Comment by billtomczak** [comment]
It may also be confusing because I was (am) maybe a little confused about what's needed here. I'm prepared for the possibility of several refinements as you work with it.

**Comment by stevejburge** [comment]
I like the way it works, I guess it just wasn't intuitive:

1) What are the top 2 boxes?

2) Once I saw that the second box was a description, I didn't know where it would appear (on the main class page?)

3) The select lesson box wasn't clear

4) Could we add a download icon to make it clear where to click? https://www.ostraining.com/class/sass/html/ Here's the main class page with icon ...
![screen shot 2016-03-29 at 5 23 48 pm](https://cloud.githubusercontent.com/assets/3868028/14124357/0935742e-f5d3-11e5-99f7-f49576d585ba.png)

**Comment by billtomczak** [comment]
I've set things up so that a single file can be used in more than one class or attached to more than one lesson in the same class. This was based on how you had done things in guru.

So there's:

* Title
* Description (will appear to the right of the title in the exercise files tab)
* dropdown of already uploaded files
* dropdown to attach to a specific lesson in the class (will show up on that's lessons page)
* a standard upload field to upload a new file

**Comment by stevejburge** [comment]
Thanks @billtomczak All that looks good. It just needs explaining a bit more ... perhaps with labels or placeholders

**Comment by billtomczak** [comment]
Excellent - that can certainly be done.

**Comment by stevejburge** [comment]
@billtomczak Possible to push out the fix for this one, please?

**Comment by billtomczak** [comment]
Soon, yes - @htmgarcia and I are zeroing in on getting the pagination issue resolved. As soon as that's done, I'll be installing the next - and hopefully last - 1.0.4 beta.

**Comment by stevejburge** [comment]
Thanks Bill. I've found a workaround for now.

**Comment by billtomczak** [comment]
@stevejburge to be clear - you're mainly asking for clarification in the admin?

**Comment by stevejburge** [comment]
@billtomczak Yes, but also the fact that you can't upload more than one file.

The second box always breaks.

**Comment by billtomczak** [comment]
ah yes - I just discovered this as a problem. Another one of those things I thought I recently fixed. Working on it.

**Comment by billtomczak** [comment]
See #242 - clearly I need to revisit

**Comment by billtomczak** [comment]
@stevejburge - sounds like this one has been taken care of. Reopen if this is not the case
