### ISSUE TITLE
Improve "class not found" message

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#237]
https://www.ostraining.com/class/fsdf/
<img width="721" alt="screen shot 2016-03-31 at 12 05 26 pm" src="https://cloud.githubusercontent.com/assets/4999794/14185860/ea6cc972-f738-11e5-8b15-c75755a5cd3a.png">

**Comment by billtomczak** [comment]
lol - oh yeah! Thanks @htmgarcia !

**Comment by htmgarcia** [comment]
@billtomczak nothing I can do here since the error comes from a model, not a view as I initially thought: https://github.com/OSTraining/OSCampus/blob/master/src/site/models/course.php#L47

**Comment by billtomczak** [comment]
Ah! Sorry about that.

**Comment by htmgarcia** [comment]
No need to say sorry, @billtomczak :)

**Comment by billtomczak** [comment]
@htmgarcia b12beaf10954799c1bad26da0be905db0e86de4e should take care of this

**Comment by htmgarcia** [comment]
Perfect. Thank you @billtomczak !
