### ISSUE TITLE
The Teacher tab needs design improvements 

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#239]
![screen shot 2016-04-01 at 11 20 35 am](https://cloud.githubusercontent.com/assets/3868028/14211374/d1023b02-f7fb-11e5-8f7f-4dc4dd35e984.png)

**Comment by stevejburge** [comment]
It looks like we're missing the social links for teachers. Maybe that's not the end of the world.

More examples ...

![screen shot 2016-04-01 at 11 22 17 am](https://cloud.githubusercontent.com/assets/3868028/14211426/09601dde-f7fc-11e5-9845-7f29ecd4e228.png)

**Comment by htmgarcia** [comment]
The first picture is big!

**Comment by htmgarcia** [comment]
@stevejburge what is the class for the first example?

**Comment by stevejburge** [comment]
That's the new WordPress API class I'm working on

Maybe we can do this? Do a quick fix now (a standard size for all images) then redesign the class layout in general?

**Comment by htmgarcia** [comment]
Ideally, images should be as maximum 400px width, however I just added some CSS to display a consistent size no matter the image's width.

The change will be available at OST once is merged into master.

**Comment by htmgarcia** [comment]
I added a smaller version of Josh Pollock's image and updated the CSS.

Thoughts about why the links from this teacher are not being displayed, @billtomczak ?
https://www.ostraining.com/class/wordpress-api/

**Comment by htmgarcia** [comment]
Nevermind. The links has settings to show/hide:
![ostraining_-_administration_-_oscampus__edit_teacher](https://cloud.githubusercontent.com/assets/4999794/14212280/5b778b8c-f7ef-11e5-8522-516d95cce8ea.jpg)
Maybe remove those settings and links should be visible when they exists, and ignore when they are empty (?)
