### ISSUE TITLE
Design for pathway pages

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#240]
Hey guys

With the Pathway pages, can we add the pathway details (image, description, number of classes) at the top? Let's tell people what they are going to learn in this pathway ...

![screen shot 2016-04-01 at 12 06 03 pm](https://cloud.githubusercontent.com/assets/3868028/14212730/41d037ac-f802-11e5-8726-56259842a732.png)

**Comment by htmgarcia** [comment]
This is a quick draft:
<img width="770" alt="screen shot 2016-04-01 at 10 18 25 am" src="https://cloud.githubusercontent.com/assets/4999794/14213046/1914044c-f7f3-11e5-9247-3e221c710b91.png">
It is something similar to this, @stevejburge ?

**Comment by stevejburge** [comment]
Yes, thanks, that's the direction.

The pathway image is a little too similar to the class images. Maybe right-align it or add some styles so that it's 100% clearly different?

**Comment by htmgarcia** [comment]
To be honest, I would rather suggest to remove pathway image to avoid any confussion.

**Comment by stevejburge** [comment]
Ok, no problem, let's play with this some more. So long as we get a very clear explanation of this pathway.

**Comment by stevejburge** [comment]
@htmgarcia Can we keep moving on this one? I'd like to do a lot of work on pathways this week.

**Comment by htmgarcia** [comment]
Update:
<img width="756" alt="screen shot 2016-04-19 at 10 27 16 am" src="https://cloud.githubusercontent.com/assets/4999794/14644928/53a1359c-0619-11e6-971a-1acd3a9284ba.png">

**Comment by htmgarcia** [comment]
Live preview: https://www.ghostexplained.com/classes/drupal/

**Comment by stevejburge** [comment]
Thanks @htmgarcia Looks good. 

Are we 100% sure we want to skip the pathway image?

**Comment by htmgarcia** [comment]
Yes.

**Comment by stevejburge** [comment]
Ok, so shall it be :)

@htmgarcia @billtomczak Possible to get this change out this week, please?

**Comment by htmgarcia** [comment]
@stevejburge [the commit has been done](https://github.com/OSTraining/OSCampus/commit/f30761e83d44a1f74025797f0db408b6c2d0408b). It depends on the next release approved by @billtomczak

**Comment by billtomczak** [comment]
Looks like this is done and v1.0.4 final was installed today.

**Comment by htmgarcia** [comment]
Thanks @billtomczak !
