### ISSUE TITLE
Lesson choose is broken for multiple files

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#242]
I've uploaded several files.

The UI always sends me back to the Lesson Picker for the first files
![screen shot 2016-04-04 at 11 06 48 am](https://cloud.githubusercontent.com/assets/3868028/14252460/76245a60-fa55-11e5-8024-ef4243761152.png)

**Comment by billtomczak** [comment]
Well, it was a really annoying mess of problems but it's fixed now!
