### ISSUE TITLE
Search design/ux

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#248]
![screen shot 2016-04-06 at 4 47 01 pm](https://cloud.githubusercontent.com/assets/906943/14334443/1984fb86-fc1a-11e5-8205-39e87861798f.png)

With the on-change, Bill's planning on getting rid of the search button too, so maybe it can look like our main search but with a different icon?

**Comment by htmgarcia** [comment]
This is how it looks with the update:
<img width="224" alt="screen shot 2016-04-07 at 2 33 06 pm" src="https://cloud.githubusercontent.com/assets/4999794/14364274/ad5c0d1e-fccd-11e5-8d62-2cddb90487b2.png">

**Comment by nicksavov** [comment]
It still seems too bulky to me. Let's:
1) get rid of the buttons
2) just have "Advanced" underneath as a link
3) put "Clear" as a link within the advanced area.

**Comment by htmgarcia** [comment]
Two new proposals:
<img width="220" alt="screen shot 2016-04-07 at 4 36 56 pm" src="https://cloud.githubusercontent.com/assets/4999794/14367673/f9c017ac-fcde-11e5-9e97-61a084e04088.png">
<img width="221" alt="screen shot 2016-04-07 at 4 36 04 pm" src="https://cloud.githubusercontent.com/assets/4999794/14367674/f9d70b92-fcde-11e5-9fee-df0c5dce5849.png">

**Comment by nicksavov** [comment]
Looks great, V! I'd go with https://cloud.githubusercontent.com/assets/4999794/14367673/f9c017ac-fcde-11e5-9e97-61a084e04088.png and also make the button smaller.
