### ISSUE TITLE
Add "osc-formfield-active" class onfocus

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#250]
@billtomczak is there an easy way to add the "osc-formfield-active" class immediately when somebody click on the field and/or is typing?

**Comment by billtomczak** [comment]
Easy to add to the text field. Not sure it makes sense for the dropdown.

On a related note, I notice I'm not adding it to the checkboxes right now.

**Comment by htmgarcia** [comment]
The checkboxes doesn't need it

**Comment by billtomczak** [comment]
@htmgarcia : let me know if this works for you

**Comment by htmgarcia** [comment]
I think this can be solved with CSS and :focus pseudo-class. I'll check later.

**Comment by billtomczak** [comment]
ummm.... already did something using js - I was asking for you to verify it works as you wanted.

The nice thing about using js, is I can set active/inactive correctly on focusout depending on field value.

**Comment by htmgarcia** [comment]
It works like a charm. Thanks @billtomczak! 
<img width="293" alt="screen shot 2016-10-18 at 2 26 16 pm" src="https://cloud.githubusercontent.com/assets/4999794/19493069/d9ae4a58-953e-11e6-9623-2c17e108eedd.png">
