### ISSUE TITLE
Design for pagination

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#251]
/class-search?text=introduction

**Comment by billtomczak** [comment]
@htmgarcia Please note - pagination has also been added to the pathways and pathway views.

**Comment by htmgarcia** [comment]
@billtomczak may we remove the tooltips that pagination generates for first two and last two links?

**Comment by htmgarcia** [comment]
Not sure if there is a setting in Joomla's code to remove them.

**Comment by billtomczak** [comment]
I think the only way to make a change like that would be to create our own chrome file.

**Comment by billtomczak** [comment]
See 22f26e8ff0c2acdac69da5068a0d5a2a501af9cf. I've moved pagination display into an OSCampus layout file. This should straighten things out. But I'm having some difficulties with page links. See #257
