### ISSUE TITLE
Add published date to class display

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#255]
@billtomczak It seems to be based on when the class was first created rather than the published date:
https://www.ostraining.com/new-classes/

@htmgarcia Could we add the published date to this view?

**Comment by stevejburge** [comment]
Update this is fixed, but @htmgarcia ... could we still add the published date?

**Comment by htmgarcia** [comment]
It will look a bit crawled:
<img width="734" alt="screen shot 2016-04-19 at 4 01 07 pm" src="https://cloud.githubusercontent.com/assets/4999794/14655434/f2ff2062-0647-11e6-87e8-1c505517e9d4.png">
Maybe remove number of lessons or the duration label?

**Comment by stevejburge** [comment]
Sounds good. Maybe remove duration as that's still only a guess?

**Comment by htmgarcia** [comment]
It seems the layout displayed here is taken from [the classes page](https://www.ostraining.com/classes/wordpress/), so, this change will apply to both sides. Is that correct @billtomczak ?

**Comment by htmgarcia** [comment]
Preview: https://www.ghostexplained.com/new-classes/

**Comment by htmgarcia** [comment]
It also applies to: /classes/wordpress/

**Comment by billtomczak** [comment]
@htmgarcia - yes - almost exactly the same display shows up in several views so this provided consistency. I think the code should be pretty clear about how that's done. So if necessary, you could create a separate template if needed

**Comment by htmgarcia** [comment]
I'm trying to skip the duplication of code - lol

**Comment by billtomczak** [comment]
@stevejburge @htmgarcia what's our status on this one?

**Comment by htmgarcia** [comment]
It's live with the new update.
https://www.ostraining.com/classes/wordpress/
https://www.ostraining.com/new-classes/

**Comment by stevejburge** [comment]
Ah, sorry to be a pain. We didn't want it applied to all views, just to "New Classes"

If it's too much work though,we can leave it

**Comment by htmgarcia** [comment]
Undoing changes.

**Comment by stevejburge** [comment]
It's a not a big, but that was the original plan.

**Comment by billtomczak** [comment]
The new layout system available in J3 provides a really nice way to create configurations for this. I've set it up using the standard display as default, but used the new options to modify the display for new classes.

@htmgarcia see [this code](https://github.com/OSTraining/OSCampus/blob/6f5a6ae96aef8f6e7f826a6bf86326bcb8c0764a/src/site/views/newcourses/tmpl/default.php#L27) for an example of how to call the rendering engine.

**Comment by htmgarcia** [comment]
Thanks @billtomczak !
