### ISSUE TITLE
Extra row on the class listings

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#256]
Just a small thing, but it looks like there's an extra line below some classes ...

![screen shot 2016-04-19 at 5 12 04 pm](https://cloud.githubusercontent.com/assets/3868028/14655767/de2dd0de-0651-11e6-93bf-2d4f8625ea07.png)

**Comment by htmgarcia** [comment]
@stevejburge do you mean in the very bottom?

**Comment by stevejburge** [comment]
Underneath "All the WordPress Theme Design Classes" there's an extra row

**Comment by htmgarcia** [comment]
Is the margin-bottom from the paragraph. The above commit fix the issue and will be live in the next release.
