### ISSUE TITLE
Moving a module inside a class

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#258]
I'm trying to edit "How to Turn Designs into Drupal 8 Themes"

I can't move these three classes at the bottom to the top
![screen shot 2016-04-21 at 9 52 03 am](https://cloud.githubusercontent.com/assets/3868028/14711342/f4bc0cd4-07a6-11e6-9fda-3c718468f4d2.png)

**Comment by billtomczak** [comment]
Yes - that is a limitation of this interface. Part of the unresolved issue of module editing in general. Lessons can moved into a different module one of two ways. 

Lesson edit - change the module name here. This won't allow ordering though.

Course edit - on the lessons page, you have total flexibility to reorganize lessons and modules. Remember that unlike guru, your changes don't take place until you save/apply for the course.

I realize this is not a great answer. At some point we need to come up with a better way.

**Comment by stevejburge** [comment]
Ah, lessons page ... I see now. Thanks

**Comment by billtomczak** [comment]
Closing. See #55
