### ISSUE TITLE
OSCampus Modules

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#263]
With the new OST design, a couple of modules will be needed to display:

- Popular videos
- A list of pathways with latest classes

[See this proposal](https://github.com/OSTraining/OSTraining-Design/issues/84#issuecomment-212567994), please. "Monthly Popular Videos" and the section below.

**Comment by htmgarcia** [comment]
Don't worry too much about the layout.

**Comment by billtomczak** [comment]
OSCampusLatest module is in development: [OSCampusLatest](https://github.com/OSTraining/OSCampusLatest)

**Comment by htmgarcia** [comment]
We have [the first module](https://github.com/OSTraining/OSCampusLatest/issues/1) in place :smile:
