### ISSUE TITLE
Batch processing 

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#270]
Definitely need batch processing please

I'd like to change the Access of 60 videos in a lesson from "Video, Personal, Pro and Admins"

This might take a while ...

**Comment by billtomczak** [comment]
@stevejburge I've implemented a first pass on batch processing for lessons. May need some tweaking for aesthetics, but it basically works.

**Comment by htmgarcia** [comment]
@billtomczak please open an issue assigned to me if any design imporvement is needed.

**Comment by stevejburge** [comment]
Wonderful, thanks @billtomczak
