### ISSUE TITLE
Class certificate not awarded when lesson is unpublished

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#272]
If there's an unpublished lesson, the user can't get the certificate. It appears that the class completion percentage includes unpublished lessons.

For example, check the "The Beginners Guide to Drupal 8" class. The "Setting Up URL Paths" lesson is unpublished. Completing all the lessons on the site gets 98%. Once the "Setting Up URL Paths" lesson is published, completing it brings the percentage up to 100%.

**Comment by nicksavov** [comment]
On OSDashboard, the class should be removed from My Classes too

**Comment by billtomczak** [comment]
The dashboard issue should be tracked here: OSTraining/OSDashboard#11
