### ISSUE TITLE
Can't override tabs language

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSCampus#273]
I couldn't seem to override the "Table of contents", "description" etc in the class tabs

**Comment by billtomczak** [comment]
@stevejburge - There shouldn't be a problem with this. You might have to clear cache after making changes though.

**Comment by stevejburge** [comment]
Thanks Bill. I just couldn't find that text in the override manager

**Comment by htmgarcia** [comment]
@stevejburge I think the constants for frontend may be located in the administrator side. Step 3 will help you figure out: https://www.ostraining.com/blog/joomla/language-constants/

**Comment by billtomczak** [comment]
Hmmm. Perplexing. The constants are on the site side. Here's the search I did

![override](https://cloud.githubusercontent.com/assets/3068131/15901710/4050a1aa-2d59-11e6-9233-ed035b485be2.jpg)

**Comment by stevejburge** [comment]
Thanks. Oddly, I still couldn't find the value, but could find the constant

**Comment by billtomczak** [comment]
Odd indeed!
