### ISSUE TITLE
Display course difficulty in course listings

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/OSCampus#275]
Replace the instructor indicator with difficulty on all course lists.

![course](https://cloud.githubusercontent.com/assets/3068131/16203149/aee2ff46-36cd-11e6-8ac0-4fd86a4f3291.jpg)

**Comment by billtomczak** [comment]
@htmgarcia  please check my choices on this.

**Comment by htmgarcia** [comment]
@billtomczak I like the idea of having settings to display/hide the information! 
btw, where in backend is this setting available?

**Comment by billtomczak** [comment]
I haven't created a UI for these settings. Right now hardcoded in the two course listing templates (pathway, newcourses). See https://github.com/OSTraining/OSCampus/blob/master/src/site/views/newcourses/tmpl/default.php#L27 for an example of using options to choose.

Creating a set of options in menu parameters would be a really simple addition.
