### ISSUE TITLE
Which code is being used?

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#278]
I think part of this code makes reference to the old template, due main tab is not present in OSCampus: https://github.com/OSTraining/OSCampus/blob/master/src/media/css/style.css#L139-L196

**Comment by htmgarcia** [comment]
Also, this line makes reference to the main tag, which is not present in OSCampus: https://github.com/OSTraining/OSCampus/blob/master/src/media/js/wistia.js#L176

I assume that code pointed to yoo_lava template

**Comment by billtomczak** [comment]
Yes it does. And so should be replaced by something OSCampus specific.

If it helps, this is what it's targeting: https://github.com/OSTraining/tpl_ostraining_lava/blob/master/src/styles/OSTraining/layouts/theme.php#L111

**Comment by htmgarcia** [comment]
I forgot to reference an update for this issue: https://github.com/OSTraining/OSCampus/commit/4c1e07aa7a0ee2036ceb149c03f27ec5d87676e3

**Comment by htmgarcia** [comment]
This is the most recent commit that target OSCampus code, not the template's one: https://github.com/OSTraining/OSCampus/commit/cedc444cbbeadc3872b5db97042daafa5d942437

This is only template dependency I found: https://github.com/OSTraining/OSCampus/commit/cedc444cbbeadc3872b5db97042daafa5d942437#diff-290f4806ec3470f74b25508ed6b1b749R230

**Comment by billtomczak** [comment]
Closing in deference to #281
