### ISSUE TITLE
The same video is played all the time with fullscreen and autoplay enabled

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#279]

**Comment by billtomczak** [comment]
Addressed by a196ad1ba13d85a888f01af6e36b42cf27f70540

Unfortunately, now every time you click on a nav button in fullscreen a new click event is added to the stack. So the fourth time you click on a nav button in fullscreen, the lesson is loaded four times.

I'll go ahead and release a new version, but all this fullscreen/navigation code needs some reworking.

**Comment by billtomczak** [comment]
Closing in deference to #281
