### ISSUE TITLE
Better explanation for single class menu item

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/OSCampus#287]
Meant as an anchor point for individual classes, not a link for a specific class.

Also might be good to provide some better response than 'class not found'

**Comment by billtomczak** [comment]
@stevejburge initial proposed solution:
![singleclass](https://cloud.githubusercontent.com/assets/3068131/18114635/7990ac14-6eed-11e6-8ec6-873a1823b689.png)

**Comment by OSTraining** [comment]
Great, thanks Bill. Perhaps, "You should only create one menu item of this type. This link provides a single URL base for all classes."
