### ISSUE TITLE
Various code issues

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#291]
See:
https://secure.helpscout.net/conversation/251341636/39418/?folderId=852196

**Comment by billtomczak** [comment]
Re:
* 001: C:\wampps\Ampps\www\362da\tmp\jed_checker\unzipped\com_oscampus_pro_1.0.5b5.zip/admin/library/joomla/controller/base.php
You've used encoding in this file? This is not an error, but an editor will have to review this file!
* 002: C:\wampps\Ampps\www\362da\tmp\jed_checker\unzipped\com_oscampus_pro_1.0.5b5.zip/admin/library/oscampus/Lesson/Type/Quiz.php
You've used encoding in this file? This is not an error, but an editor will have to review this file!

use of base64_decode seems to be flagged here. No way around it as it's a standard way of passing a url as a url parameter. Joomla core itself does exactly the same thing. See the login processing form for example

**Comment by billtomczak** [comment]
re: 
* 001 C:\wampps\Ampps\www\362da\tmp\jed_checker\unzipped\com_oscampus_pro_1.0.5b5.zip/admin/library/Installer/AbstractScript.php in line: 225
Are we procrastinating?:
        // @TODO: Stop the script here if this is a related extension (but still remove pro folder, if needed) 

This is an issue for https://github.com/OSTraining/AllediaInstaller

**Comment by billtomczak** [comment]
re:
* 001 C:\wampps\Ampps\www\362da\tmp\jed_checker\unzipped\com_oscampus_pro_1.0.5b5.zip/extensions/plg_osmap_com_oscampus/com_oscampus.php in line: 30
You shouldn't use superglobals:

    \* @var string Value for $_GET param 'option' 

This references a code comment and is irrelevant

**Comment by billtomczak** [comment]
Re:

* 001 C:\wampps\Ampps\www\362da\tmp\jed_checker\unzipped\com_oscampus_pro_1.0.5b5.zip/extensions/plg_osmap_com_oscampus/com_oscampus.php in line: 30
You shouldn't use superglobals:
    * @var string Value for $_GET param 'option' 

non-issue: hardcoded MySQL object name quotes for undocumented backend utilities

**Comment by billtomczak** [comment]
All issues in the ticket have been addressed
