### ISSUE TITLE
Adapt for new OSWistia and Wistia's Vulcan player

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSCampus#292]
It breaks because the new OSWistia loads the script asynchronously, so the "wistiaEmbed" variable is not loaded instantaneously. Maybe need to use _wq, instead of wistiaEmbed.onReady....

**Comment by billtomczak** [comment]
Fixed by f7189a6235a61a954ce63adc1e6ae7b4bc5f036c

Although this feels like a bit of a precarious solution
