### ISSUE TITLE
Error message when creating a new class

### ISSUE THREAD

**Issue by JurgenG** [OSTraining/OSCampus#301]
Hi,

when creating a new class (no lessons exist yet, because I need to have a class to create lessons), I get the following error message: 
0 SplFileInfo::__construct() expects parameter 1 to be string, array given 

Please contact me if you need a login to the test site...

**Comment by billtomczak** [comment]
Hi JurgenG and thanks!

We saw an error like that during our testing and it turned out to be caused by another plugin. In our case it was JHackguard. So I suspect you will find that is the case here. Please review any other plugins you may have installed and let us know.

**Comment by JurgenG** [comment]
Hi Bill,
I indeed have JHackguard installed by default on my systems (I'm running at Siteground). Would you call this a bug in JHackguard or in OSCampus? I consider both of you really skilled and I'd hope the two of you together will work this out :)

**Comment by billtomczak** [comment]
Hey JugenG;

I've examined the code carefully and see where the problem is in JHackguard. I've submitted a ticket to SiteGround from our account. We'll let let you know how it turns out.

Thanks for the spur on this!

-bill

**Comment by billtomczak** [comment]
btw - I just discovered that you can turn of the scan of files in the JHackGuard component:

<img width="379" alt="screen shot 2016-10-27 at 3 12 28 pm" src="https://cloud.githubusercontent.com/assets/3068131/19787514/08bfddaa-9c58-11e6-982e-12b1137a8f60.png">

**Comment by billtomczak** [comment]
Hi again JurgenG;

I noticed that someone else reported this same problem using 'Component Creator'. I submitted a ticket and SiteGround support has said only that they've put my report into their system.

 It looks like that's about as far as I can take this from our end. I would suggest turning off the file scanning as described above until there's news that they've fixed their code.

-bill

**Comment by JurgenG** [comment]
Thanks a lot! I'm quite certain the wonderful people at Siteground will have this issue fixed in no time (just like you guys also took it on as far as you could) :)
