### ISSUE TITLE
Missing language string

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#305]
> COM_OSCAMPUS_TEACHER_LINK_default

**Comment by htmgarcia** [comment]
<img width="421" alt="screen shot 2016-11-08 at 10 42 52 am" src="https://cloud.githubusercontent.com/assets/4999794/20107971/1e6f1e30-a5a0-11e6-9fc4-834499e8c632.png">

**Comment by billtomczak** [comment]
In theory, that language constant shouldn't ever show up. Can you provide a means (or a link) to reproduce this?

**Comment by htmgarcia** [comment]
I'm working this on local. It seems to be the G+ plus label

**Comment by billtomczak** [comment]
Thanks, that helps!

**Comment by htmgarcia** [comment]
Thanks @billtomczak!
