### ISSUE TITLE
Hidden JS logo

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#306]
<img width="413" alt="screen shot 2016-11-08 at 12 09 03 pm" src="https://cloud.githubusercontent.com/assets/4999794/20110987/2d2a4b96-a5ac-11e6-85f4-91077631348f.png">

**Comment by billtomczak** [comment]
Should be resolved by 69feeed0b84e5bd5674b37f2096b9d08d6fd3fe6

**Comment by htmgarcia** [comment]
Thanks @billtomczak!
