### ISSUE TITLE
Missing language strings

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#308]
OSCampus 1.0.6
<img width="762" alt="screen shot 2016-11-09 at 10 16 15 am" src="https://cloud.githubusercontent.com/assets/4999794/20145413/af6eb2ea-a665-11e6-914e-ad73e1142009.png">

**Comment by billtomczak** [comment]
@anderson -- Where does the allediainstaller language file get loaded?

**Comment by andergmartins** [comment]
That missed strings I see on the image should come from OSSystem. Are like global strings.

But the ones ref the installer are loaded here:

https://github.com/OSTraining/AllediaInstaller/blob/master/src/library/Installer/AbstractScript.php#L165
https://github.com/OSTraining/AllediaInstaller/blob/master/src/library/Installer/AbstractScript.php#L323
https://github.com/OSTraining/AllediaInstaller/blob/master/src/library/Installer/AbstractScript.php#L194

**Comment by billtomczak** [comment]
Thanks - I figured it out before I saw your response :)

I needed to reconfigure the jenkins job to include OSSystem.

**Comment by billtomczak** [comment]
@htmgarcia -- the installer for 1.0.6 on github has been updated to address this issue

**Comment by htmgarcia** [comment]
Thanks @billtomczak!
