### ISSUE TITLE
Admin: need files field

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/OSCampus#52]
To handle attaching files to courses and lessons

**Comment by htmgarcia** [comment]
Note to myself: check example in test site for "Introduction to Responsive Design" class. 
Use the UI from quizes.

**Comment by htmgarcia** [comment]
@billtomczak I tried to add an empty space between the plus icon and "Add File" string. Thoughts?
Is the only thing missing to close this issue.

**Comment by billtomczak** [comment]
Easy peasy!
