### ISSUE TITLE
Focus button doesn't appear to do anything after clicked

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#66]

**Comment by billtomczak** [comment]
@nicksavov, are there any remaining issues on this one?

**Comment by nicksavov** [comment]
Not that I'm aware of. You mentioned "I was still seeing some not so great behavior", but I wasn't able to spot anything.

**Comment by billtomczak** [comment]
Yeah - I can't remember what the issues I saw were, but I think they've been all addressed now.
