### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSCampus#68]
Check from [here](https://github.com/OSTraining/OSCampus/tree/progress-bar)

Relevant code: https://github.com/OSTraining/OSCampus/blob/progress-bar/src/site/views/mycourses/tmpl/default.php#L41-L43

**Comment by billtomczak** [comment]
Closing since it looks like #48 took care of this

**Comment by htmgarcia** [comment]
Thanks @billtomczak !
