### ISSUE TITLE
Video image https

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSCampus#70]
Go to https://www.ostraining.com/courses-osc/wordpress/why/introduction/ when not logged in. It's showing the SSL cert as yellow instead of green.

It's coming from:
`<image src="http://embed.wistia.com/deliveries/704fc18e243d068ab64a120b2c4df15820ceba34.bin" width="900" height="504"/>`

**Comment by billtomczak** [comment]
@nicksavov - As it turns out, the Wistia api docs say to do exactly this manipulation when needed. So a really easy solution as it turns out!

**Comment by nicksavov** [comment]
Great, glad to hear that! :)
